---
version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "."
    schedule:
      interval: "monthly"
    groups:
      gomod:
        patterns: ["*"]
    labels: ["area/dependencies"]
  - package-ecosystem: "docker"
    directory: "."
    schedule:
      interval: "monthly"
    groups:
      docker:
        patterns: ["*"]
    labels: ["area/dependencies"]
