---
name: "Build & Test"
on:  # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - "*"
  merge_group:
    types:
      - "checks_requested"
jobs:
  build:
    name: "Build Binary"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "authzed/actions/setup-go@main"
      - uses: "authzed/actions/go-build@main"

  unit:
    name: "Run Unit Tests"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "authzed/actions/setup-go@main"
      - uses: "authzed/actions/go-test@main"
