---
name: "release"
on:  # yamllint disable-line rule:truthy
  release:
    types:
      - "published"

jobs:
  github:
    runs-on: "macos-latest"
    steps:
      - uses: "actions/checkout@v4"
        with:
          fetch-depth: 0
      - uses: "authzed/actions/setup-go@main"
      - uses: "authzed/actions/docker-login@main"
        with:
          quayio_token: "${{ secrets.QUAYIO_PASSWORD }}"
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          dockerhub_token: "${{ secrets.DOCKERHUB_ACCESS_TOKEN }}"
      - uses: "goreleaser/goreleaser-action@v6"
        with:
          distribution: "goreleaser-pro"
          # NOTE: keep in sync with goreleaser version in other job.
          # github actions don't allow yaml anchors.
          version: "2.4.8"
          args: "release --clean"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          GORELEASER_KEY: "${{ secrets.GORELEASER_KEY }}"
